// Copyright (c) Microsoft Corporation.
// Licensed under the MIT license.
//
// Build-time codegen: derive the ETW provider name and the four
// `MICROSOFT_KEYWORD_*` / `PDT_*` numeric stubs from the C++ side, so the
// Rust telemetry surface stays in lockstep with the C++ telemetry surface
// without a second set of literals.
//
// Sources read:
//   - ../../src/cascadia/TerminalApp/init.cpp       (provider name)
//   - ../../dep/telemetry/ProjectTelemetry.h        (four numeric stubs)
//
// These are the same two files an internal-build overlay (the
// `Microsoft.Windows.Terminal.Versioning` NuGet `Setup.ps1`) rewrites. By
// reading them here at build time we get exactly one source of truth for
// both languages: whatever the overlay (or OSS) leaves on disk at
// pipeline-cargo-build time is what the resulting `wta.exe` reports.
//
// In OSS the resulting `telemetry_codegen.rs` looks like:
//
//   tracelogging::define_provider!(
//       AGENT_PROVIDER,
//       "Microsoft.Windows.Terminal.App",
//       group_id("9aa7a361-583f-4c09-b1f1-cea1ef5863b0")
//   );
//   #[allow(dead_code)] pub const MICROSOFT_KEYWORD_MEASURES: u64       = 0x0;
//   #[allow(dead_code)] pub const MICROSOFT_KEYWORD_TELEMETRY: u64      = 0x0;
//   pub const PDT_PRODUCT_AND_SERVICE_USAGE: u64                        = 0x0;
//   pub const PDT_PRODUCT_AND_SERVICE_PERFORMANCE: u64                  = 0x0;
//
// The Microsoft telemetry group GUID
// (`9aa7a361-583f-4c09-b1f1-cea1ef5863b0`) is a public, well-known
// constant pinned both here and on the C++ side
// (`TraceLoggingOptionMicrosoftTelemetry`).
//
// We deliberately use no external build-dependencies (no `regex` crate).
// Five fixed lookups against two small files — hand-rolled scanning is
// simpler to audit and keeps the build closure flat.

use std::env;
use std::fs;
use std::path::{Path, PathBuf};

/// Microsoft Telemetry option group GUID — public well-known constant,
/// identical in OSS and Microsoft-internal builds. Mirrors the C++ macro
/// `TraceLoggingOptionMicrosoftTelemetry()` defined in
/// `dep/telemetry/ProjectTelemetry.h`.
const MICROSOFT_TELEMETRY_GROUP_GUID: &str = "9aa7a361-583f-4c09-b1f1-cea1ef5863b0";

fn main() {
    // Set the default thread stack size to 8 MB on Windows debug builds.
    //
    // Why this is needed:
    //   rust-i18n v3 embeds all translations at compile time. Each `t!()`
    //   call-site expands into a match over every available locale (~89).
    //   In unoptimized (debug) builds the compiler does not collapse these
    //   match arms, so functions that contain several `t!()` calls produce
    //   stack frames large enough to overflow the default 1 MB stack.
    //
    //   Release builds are unaffected — the optimizer folds the match arms
    //   and keeps stack usage well within 1 MB.
    //
    // 8 MB is a conservative choice — many Windows desktop applications
    // (including the .NET CLR) default to 4–8 MB stacks.
    #[cfg(all(debug_assertions, target_os = "windows", target_env = "msvc"))]
    println!("cargo:rustc-link-arg=/STACK:8388608");

    let manifest_dir = PathBuf::from(env::var_os("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR"));
    // tools/wta -> repo root
    let repo_root = manifest_dir
        .parent()
        .and_then(Path::parent)
        .unwrap_or_else(|| panic!("could not derive repo root from {}", manifest_dir.display()))
        .to_path_buf();

    let init_cpp = repo_root.join("src/cascadia/TerminalApp/init.cpp");
    let proj_tel_h = repo_root.join("dep/telemetry/ProjectTelemetry.h");

    println!("cargo:rerun-if-changed=build.rs");
    println!("cargo:rerun-if-changed={}", init_cpp.display());
    println!("cargo:rerun-if-changed={}", proj_tel_h.display());

    let provider_name = extract_provider_name(&init_cpp);
    let keyword_measures = extract_define_u64(&proj_tel_h, "MICROSOFT_KEYWORD_MEASURES");
    let keyword_telemetry = extract_define_u64(&proj_tel_h, "MICROSOFT_KEYWORD_TELEMETRY");
    let privacy_usage = extract_define_u64(&proj_tel_h, "PDT_ProductAndServiceUsage");
    let privacy_perf = extract_define_u64(&proj_tel_h, "PDT_ProductAndServicePerformance");

    let out_dir = PathBuf::from(env::var_os("OUT_DIR").expect("OUT_DIR"));
    let out_path = out_dir.join("telemetry_codegen.rs");
    let generated = format!(
        "// Generated by build.rs from:\n\
         //   {init_cpp}\n\
         //   {proj_tel_h}\n\
         // Do not edit by hand.\n\
         \n\
         tracelogging::define_provider!(\n    \
             AGENT_PROVIDER,\n    \
             {provider_name:?},\n    \
             group_id({group_id:?})\n\
         );\n\
         \n\
         #[allow(dead_code)]\n\
         pub const MICROSOFT_KEYWORD_MEASURES: u64 = {keyword_measures:#x};\n\
         #[allow(dead_code)]\n\
         pub const MICROSOFT_KEYWORD_TELEMETRY: u64 = {keyword_telemetry:#x};\n\
         pub const PDT_PRODUCT_AND_SERVICE_USAGE: u64 = {privacy_usage:#x};\n\
         pub const PDT_PRODUCT_AND_SERVICE_PERFORMANCE: u64 = {privacy_perf:#x};\n",
        init_cpp = init_cpp.display(),
        proj_tel_h = proj_tel_h.display(),
        provider_name = provider_name,
        group_id = MICROSOFT_TELEMETRY_GROUP_GUID,
        keyword_measures = keyword_measures,
        keyword_telemetry = keyword_telemetry,
        privacy_usage = privacy_usage,
        privacy_perf = privacy_perf,
    );
    fs::write(&out_path, generated).unwrap_or_else(|e| {
        panic!("failed to write {}: {e}", out_path.display());
    });
}

/// Read the provider name from a `TRACELOGGING_DEFINE_PROVIDER(...)`
/// invocation. The macro spans multiple lines:
///
/// ```c
/// TRACELOGGING_DEFINE_PROVIDER(
///     g_hTerminalAppProvider,
///     "Microsoft.Windows.Terminal.App",
///     (0x..., ...),
///     TraceLoggingOptionMicrosoftTelemetry());
/// ```
///
/// Strategy: find the macro literal, then locate the first double-quoted
/// string that follows. Panics with a clear message on miss so the build
/// fails loudly rather than silently emitting the wrong provider name.
fn extract_provider_name(path: &Path) -> String {
    let text = fs::read_to_string(path)
        .unwrap_or_else(|e| panic!("failed to read {}: {e}", path.display()));
    let macro_name = "TRACELOGGING_DEFINE_PROVIDER";
    let macro_pos = text.find(macro_name).unwrap_or_else(|| {
        panic!(
            "{macro_name} not found in {}; the file layout this build.rs depends on has changed",
            path.display()
        )
    });
    // Find the first '"' after the macro opens. We tolerate any whitespace
    // / comments / identifier (the handle name) and the comma before the
    // string literal.
    let after_macro = &text[macro_pos + macro_name.len()..];
    let first_quote = after_macro.find('"').unwrap_or_else(|| {
        panic!(
            "no string literal found after {macro_name} in {}",
            path.display()
        )
    });
    let after_quote = &after_macro[first_quote + 1..];
    let closing = after_quote.find('"').unwrap_or_else(|| {
        panic!(
            "unterminated string literal after {macro_name} in {}",
            path.display()
        )
    });
    after_quote[..closing].to_string()
}

/// Parse a `#define NAME <integer>` line, accepting common C numeric
/// suffixes (`u`, `U`, `ul`, `ULL`, …) and both hex (`0x...`) and decimal
/// literals. Panics if the constant is missing.
fn extract_define_u64(path: &Path, name: &str) -> u64 {
    let text = fs::read_to_string(path)
        .unwrap_or_else(|e| panic!("failed to read {}: {e}", path.display()));
    for line in text.lines() {
        let trimmed = line.trim_start();
        let rest = match trimmed.strip_prefix("#define") {
            Some(r) => r.trim_start(),
            None => continue,
        };
        let rest = match rest.strip_prefix(name) {
            // The character immediately after `name` must not be an
            // identifier-continuation char; without this guard
            // `MICROSOFT_KEYWORD_X` would also match `MICROSOFT_KEYWORD_XY`.
            Some(r) if r.chars().next().is_none_or(|c| !is_ident_continue(c)) => r.trim_start(),
            _ => continue,
        };
        // Strip a trailing comment, if any.
        let value_text = rest
            .split_once("//")
            .map(|(v, _)| v)
            .unwrap_or(rest)
            .trim();
        // Strip a C numeric suffix.
        let digits_end = value_text
            .find(|c: char| !(c.is_ascii_hexdigit() || c == 'x' || c == 'X'))
            .unwrap_or(value_text.len());
        let digits = &value_text[..digits_end];
        let parsed = if let Some(hex) = digits.strip_prefix("0x").or_else(|| digits.strip_prefix("0X")) {
            u64::from_str_radix(hex, 16)
        } else {
            digits.parse::<u64>()
        };
        return parsed.unwrap_or_else(|e| {
            panic!(
                "failed to parse `#define {name} {value_text}` in {}: {e}",
                path.display()
            )
        });
    }
    panic!(
        "`#define {name} ...` not found in {}; the file layout this build.rs depends on has changed",
        path.display()
    );
}

fn is_ident_continue(c: char) -> bool {
    c == '_' || c.is_ascii_alphanumeric()
}
