// Copyright (c) Microsoft Corporation.
// Licensed under the MIT license.

import "AIAgentsViewModel.idl";

namespace Microsoft.Terminal.Settings.Editor
{
    [default_interface] runtimeclass AIAgents : Windows.UI.Xaml.Controls.Page
    {
        AIAgents();
        AIAgents(Microsoft.Terminal.Settings.Model.GlobalAppSettings globalSettings);
        AIAgentsViewModel ViewModel { get; };

        static Double InstalledOpacity(Boolean isInstalled);
        static Boolean NotBool(Boolean value);
    }
}
