mod agent_popup;
pub mod agents_view;
mod auth;
pub(crate) mod card;
pub(crate) mod chat;
mod command_popup;
mod debug_panel;
mod input;
mod layout;
pub(crate) mod markdown;
mod model_popup;
mod permission;
mod popup;
mod recommendations;
mod shell_sessions_view;
pub mod setup;
pub mod shimmer;

pub use agent_popup::AgentPopupState;
pub use command_popup::{PopupCandidates, PopupState};
pub use layout::render;
pub use model_popup::ModelPopupState;
pub use shell_sessions_view::ShellSessionsViewState;
pub use shimmer::CYCLE_FRAMES as ACTIVITY_CYCLE_FRAMES;
